version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
      - "ruby"

  - package-ecosystem: "bundler"
    directory: "/spec/tester_mongo/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
      - "ruby"

  - package-ecosystem: "bundler"
    directory: "/spec/tester_mongo_rails_6/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "rails"
        update-types: ["version-update:semver-major"]
    labels:
      - "dependencies"
      - "ruby"
