development:
  clients:
    default:
      database: graphoid
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: graphoid_test
      hosts:
        - localhost:27017
