development:
  clients:
    default:
      database: digitalize
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: digitalize_test
      hosts:
        - localhost:27017
