development:
  clients:
    default:
      database: digitalize
      hosts:
        - localhost:32768

test:
  clients:
    default:
      database: digitalize_test
      hosts:
        - localhost:32768
