# frozen_string_literal: true

source 'https://rubygems.org'

gem 'puma', '~> 3.7'
gem 'rails', '~> 6.0'
gem 'sqlite3'

gem "nokogiri", "~> 1.13.9"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
end

gem 'graphiql-rails', '~> 1.7.0', group: :development
gem 'graphql', '~> 1.8.18'

gem 'graphoid', path: '../../'
