name: CI

on:
  pull_request:
    types: [opened, synchronize, edited, reopened, review_requested, ready_for_review]
    paths: ['**/*.rb', '**/*.yml', '**/*.ru', '**/*.erb', '**/*.lock', '**/*.gemspec']

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  ubuntu-latest-make:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v1

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install build-essential software-properties-common
          sudo apt-add-repository -y ppa:rael-gc/rvm
          sudo apt-get install rvm
          sudo usermod -a -G rvm $USER

      - name: Tests
        id: rspec
        run: |
          DRIVER=ar bundle exec rspec
